parameters:
#    piotr_hello.example.class: Piotr\HelloBundle\Example

services:
#    piotr_hello.example:
#        class: %piotr_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
